// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  // serverUrl: 'http://localhost:8889',
  serverUrl: 'http://www.marbomil.co.rs',
  defaultLanguage: 'sr-Latn',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
