// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'http://178.222.248.47:8889',
  defaultLanguage: 'sr-Latn',
  supportedLanguages: [
    'en-US',
    'sr-Latn',
    'rus',
    'alb'
  ]
};
