// <auto-generated />
namespace Marbomil.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Product_DiscountDate_Null : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Product_DiscountDate_Null));
        
        string IMigrationMetadata.Id
        {
            get { return "201807111641124_Product_DiscountDate_Null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
