// <auto-generated />
namespace Marbomil.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OrderItem_Quantity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderItem_Quantity));
        
        string IMigrationMetadata.Id
        {
            get { return "201907081918262_OrderItem_Quantity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
