// <auto-generated />
namespace Marbomil.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class User_Additional_fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Additional_fields));
        
        string IMigrationMetadata.Id
        {
            get { return "201906231621572_User_Additional_fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
